jasypt:
  encryptor:
    password: {PASSSSSS}
    property:
      prefix: "ENC("
      suffix: ")"
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: aloaluale
api:
  baseUrl: http://url/api-landing-page/v1
  username: {username}
  password: {password}
  endpoint:
    inquiry: /api-landing-page/v1/warehouse/process
card:
  baseUrl: http://url/api-landing-page/v1
  endpoint:
    checkExit: /check-phone-exists
    upsertPhoneToken: /upsert-phone-token
    upsertMobileCard: /upsert-mobile-card
    findPhoneAndToken: /find-phone-token
    findFirstStatusBrandPrice: /find-first-status-brand-price
    getActivePriceByBrand: /get-active-price-by-brand
