jasypt:
  encryptor:
    password: 12341234
    property:
      prefix: "ENC("
      suffix: ")"
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: aloaluale
api:
  baseUrl: http://10.252.116.84:7074
  username: landingpage
  password: abc123
  endpoint:
    inquiry: /api-landing-page/v1/warehouse/process
card:
  baseUrl: http://10.252.116.84:7056/api-landing-page/v1
  endpoint:
    checkExit: /check-phone-exists
    upsertPhoneToken: /upsert-phone-token
    upsertMobileCard: /upsert-mobile-card
    findPhoneAndToken: /find-phone-token
    findFirstStatusBrandPrice: /find-first-status-brand-price
    getActivePriceByBrand: /get-active-price-by-brand